name: CrateUI
main: CrateUI\Main
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 1.0
author: xXNiceYT

commands:
 crate:
  description: "Open Crate GUI"

permissions:
 crate.key:
  description: "get key permission"
